name: CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    uses: actions/checkout@v3
    - name: CMake
      - run: mkdir -p build
      - run: cd build
      - run: cmake ..
    - name: Make
      - run: make


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    uses: actions/checkout@v3
    - name: Test
      - run: ctest --output-on-failure


